packages:
  - docs
  - playground
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^5.2.1
    '@nuxt/eslint-config': ^1.9.0
    eslint: ^9.33.0
    typescript: ~5.6.3
  nuxt:
    '@nuxt/kit': ^3.16.0
    '@nuxt/schema': ^3.16.0
    nuxt: ^3.16.0
