shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - tailwind-merge@2.6.1
  - rollup@3.30.0
  - semver@6.3.1
  - undici@5.29.0

packages:
  - docs
  - playground
  - examples/*

catalog:
  vue-router: ^5.2.0

catalogs:
  dev:
    '@antfu/eslint-config': ^9.3.0
    '@nuxt/eslint-config': ^1.17.0
    eslint: ^10.8.1
    typescript: ~5.9.3
  docs:
    docus: ^5.12.3
  nuxt:
    '@nuxt/kit': ^4.5.2
    '@nuxt/module-builder': ^1.0.3
    '@nuxt/schema': ^4.5.2
    '@nuxt/test-utils': ^4.1.0
    '@nuxt/vite-builder': ^4.5.2
    nuxt: ^4.5.2

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - unrs-resolver
  - vue-demi

allowBuilds:
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
